### ISSUE TITLE
PNG not appearing for biomes - 1.20.4

### ISSUE THREAD

**Issue by tannernola** [JorisDeBeer/Visual-travelers-title-addon#2]
Not sure why it is not working, maybe it has to do with the JSON being a slightly different format than other addons for this mod. Doesn't work by itself with mods and all required API's for the mod. Other addons with PNG titles work fine, this one does not.

![Screenshot 2024-03-31 003418](https://github.com/JorisDeBeer/Visual-travelers-title-addon/assets/165547842/b7fe0ba0-2600-456e-bd30-0b0af5a7e9a3)

**Comment by ABSOLUTEMAX123** [comment]
been having this issue as well

**Comment by andrej-petrovic** [comment]
I did some testing and it looks like the images are too big. From experimentation, I think the maximum allowed height is 256 pixels. I used imagemagick to batch-resize them to that height, and after that it seemed to work. Unfortunately at that resolution they're not very pretty.

**Comment by Jack-Chronicle** [comment]
Having the same issue, tried resizing the images to have a height no more than 256p but it didn't help

Has anyone else been able to find a way to get this to work?

**Comment by JorisDeBeer** [comment]
I will probably look at it in my coming vacation. Havent played minecraft in a while. Is it only on 1.20.4? Travelers titles probably changed something while updating.

**Comment by Cyph3rous** [comment]
noticed this in 1.20.1 as well.

**Comment by JorisDeBeer** [comment]
Coming back to you I got some time to figure it out. Is indeed the resolution what suddenly causes problems. I will be updating soon when I remade the textures. Then I will close the issue.

**Comment by JorisDeBeer** [comment]
Done
